---

- name: Deploy nginx app pods
  command: kubectl create -f http://k8s.io/docs/tasks/run-application/deployment.yaml
  ignore_errors: false
  async: 30
  poll: 15
  register: nginx_pod_create
- debug:
    var: nginx_pod_create.stdout

- name: List pods
  command: kubectl get pods -o wide
  register: get_pods
- debug:
    var: get_pods.stdout

- name: Expose service for nginx app
  command: kubectl expose deployment nginx-deployment --type=NodePort --name=nginx-service
  ignore_errors: false

- name: Get nginx service status
  shell: kubectl describe svc nginx-service
  register: nginx_svc_status
- debug:
    var: nginx_svc_status.stdout
