---

# Setup hosts and k8s package installation

- hosts: all-k8s-hosts
  vars_files:
    - group_vars/all
  roles:
    - 1-k8s-pkgs

- hosts: k8s-master
  vars_files:
    - group_vars/all
  roles:
    - 2-master-init

#- hosts: k8s-master
#  vars_files:
#    - group_vars/all
#  roles:
#    - 3-kubelet-cni-fix

- hosts: k8s-master
  vars_files:
    - group_vars/all
  roles:
    - 5-patch-kube-dns


- hosts: k8s-master
  vars_files:
    - group_vars/all
  roles:
    - 4-contrail-install

- hosts: k8s-workers
  vars_files:
    - group_vars/all
  roles:
    - 6-add-workers

- hosts: k8s-master
  vars_files:
    - group_vars/all
  roles:
    - 7-nodes-status
